version: '3'

services:
  node-app:
    build: .
    container_name: node-app
    ports:
      - 3000:3000
    env_file:
      - ./.env
    networks:
      - node-app-net
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rakib
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - node-app-net
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    networks:
      - node-app-net
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rakib
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
    # volumes:
    #   - mongo-data:/data/db
    depends_on:
      - mongo

networks:
  node-app-net:

volumes:
  mongo-data:
