import { Metadata } from 'next';
import { Fira_Code } from 'next/font/google';
import React from 'react';
import './globals.css';

const firaCode = Fira_Code({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Learning Next.js 13',
  description: 'Generated by Me',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={firaCode.className}>{children}</body>
    </html>
  );
}
